### ISSUE TITLE
Fatal error in tck.php on new install

### ISSUE THREAD

**Issue by zecakeh** [e-venement/e-venement#621]
I just installed your software following the blog article for 2.10. However I installed the master branch (v2.12.6 it seems). I cannot access any page using tck.php. tck_dev.php returns the following errors:

```
Warning: Missing argument 2 for Symfony\Component\ClassLoader\ApcClassLoader::__construct(), called in /var/www/html/e-venement/plugins/liClassLoaderPlugin/lib/liClassLoader.class.php on line 36 and defined in /var/www/html/e-venement/plugins/liClassLoaderPlugin/lib/vendor/externals/symfony2/src/Symfony/Component/ClassLoader/ApcClassLoader.php on line 72
 
Notice: Undefined variable: decorated in /var/www/html/e-venement/plugins/liClassLoaderPlugin/lib/vendor/externals/symfony2/src/Symfony/Component/ClassLoader/ApcClassLoader.php on line 78
 
Fatal error: Uncaught InvalidArgumentException: The class finder must implement a "findFile" method. in /var/www/html/e-venement/plugins/liClassLoaderPlugin/lib/vendor/externals/symfony2/src/Symfony/Component/ClassLoader/ApcClassLoader.php:79 Stack trace: #0 /var/www/html/e-venement/plugins/liClassLoaderPlugin/lib/liClassLoader.class.php(36): Symfony\Component\ClassLoader\ApcClassLoader->__construct('S2A') #1 /var/www/html/e-venement/plugins/liClassLoaderPlugin/lib/liClassLoader.class.php(41): liClassLoader->__construct() #2 /var/www/html/e-venement/plugins/sfDomPDFPlugin/config/sfDomPDFPluginConfiguration.class.php(31): liClassLoader::create() #3 /var/www/html/e-venement/lib/vendor/externals/symfony1/lib/config/sfApplicationConfiguration.class.php(169): sfDomPDFPluginConfiguration->initialize() #4 /var/www/html/e-venement/lib/vendor/externals/symfony1/lib/config/sfApplicationConfiguration.class.php(150): sfApplicationConfiguration->initializePlugins() #5 /var/www/html/e-venement/lib/vendor/externals/symfony1/lib/config/s in /var/www/html/e-venement/plugins/liClassLoaderPlugin/lib/vendor/externals/symfony2/src/Symfony/Component/ClassLoader/ApcClassLoader.php on line 79
```

It's on a Raspberry Pi running Raspbian Stretch with php7.0.

**Comment by FanchTheSystem** [comment]
Hello,please try with php5.6, as E-venement does not work with newer version of php.

**Comment by Fabrice-li** [comment]
Hi !
This is a mistake. e-venement 2 does not and will not work with php 7.
